// meta data
import Head from 'next/head';

// Recoil
import { useRecoilValue, useSetRecoilState } from 'recoil';
import {
	shuffledCardsState,
	beginRoundState,
	endRoundState,
} from '../store/atom';

// Components
import SplashPage from '@/components/splash/SplashPage';
import Header from '@/components/common/Header';

// Hooks
import { useEffect, useState } from 'react';
import { useShuffleCards } from '@/hooks/useShuffleCards';

// Type
import { CardData } from '@/types/card';

export default function Home() {
	const [splashPage, setSplashPage] = useState(true);

	const shuffledCards = useRecoilValue(shuffledCardsState);
	const beginRound = useRecoilValue(beginRoundState);
	const endRound = useRecoilValue(endRoundState);

	const setShuffledCards = useSetRecoilState(shuffledCardsState);

	const updateShuffledCards = (newCards: CardData[]) => {
		setShuffledCards(newCards);
	};

	const { shuffleCards } = useShuffleCards();

	useEffect(() => {
		if (shuffleCards.length < 75 && !beginRound) {
			const cardShuffled = shuffleCards();
			setShuffledCards(cardShuffled);
		}

		const timer = setTimeout(() => {
			setSplashPage(false);
		}, 1200);

		return () => {
			clearTimeout(timer);
		};
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main>{splashPage && <SplashPage />}</main>
		</>
	);
}
